image: registry.cn-shanghai.aliyuncs.com/choerodon-tools/cibase:0.9.1

stages:
  - build
  - release

build:
  stage: build
  script:
    - update_pom_version
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test -Dmaven.test.failure.ignore=true -DskipTests=false -U
#    - >-
#        mvn --batch-mode verify sonar:sonar
#        -Dsonar.host.url=$SONAR_URL
#        -Dsonar.login=$SONAR_LOGIN
#        -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
#        -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
#        -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
#        -Dsonar.analysis.serviceGroup=$GROUP_NAME
#        -Dsonar.analysis.commitId=$CI_COMMIT_SHA
#        -Dsonar.projectKey=${GROUP_NAME}:${PROJECT_NAME}
#    - mvn package spring-boot:repackage
#    - mv target/app.jar $PWD/docker
#    - kaniko -c $PWD/docker -f $PWD/docker/Dockerfile -d ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
  only:
    refs:
      - /^feature-.*$/
    variables:
      - $COMBINE == "true"

build-combine:
  stage: build
  script:
    - update_pom_version
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test -Dmaven.test.failure.ignore=true -DskipTests=false -U
    - >-
      mvn --batch-mode verify sonar:sonar
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_LOGIN
      -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.analysis.serviceGroup=$GROUP_NAME
      -Dsonar.analysis.commitId=$CI_COMMIT_SHA
      -Dsonar.projectKey=${GROUP_NAME}:${PROJECT_NAME}
    - mvn package spring-boot:repackage
    - mv target/app.jar docker
    - npm install --registry https://nexus.choerodon.com.cn/repository/choerodon-npm/ --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
    - chmod -R 755 node_modules
#    - npm run dist
#    - mv src/main/resources/lib/dist docker
    - npm run compile
    - echo '//${NPM_REGISTRY}:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --registry https://nexus.choerodon.com.cn/repository/private-npm/
    - curl -X POST -F token=${FRONT_REPOSITORY_TOKEN} -F ref=${REF_NAME} https://code.choerodon.com.cn/api/v4/projects/2760/trigger/pipeline
#    - kaniko -c $PWD/docker -f $PWD/docker/Dockerfile-combine -d ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
    - kaniko -c $PWD/docker -f $PWD/docker/Dockerfile -d ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
  only:
    refs:
      - master
      - tags
      - /^release-.*$/
      - /^hotfix-.*$/
    variables:
      - $COMBINE == "true"

release:
  stage: release
  script:
    - chart_build
  only:
    refs:
      - master
      - tags
      - /^release-.*$/
      - /^hotfix-.*$/
    variables:
      - $COMBINE == "true"

.auto_devops: &auto_devops |
    http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
    if [ "$http_status_code" != "200" ]; then
      cat .auto_devops.sh
      exit 1
    fi
    source .auto_devops.sh

before_script:
  - *auto_devops
